/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.premnirmal.Magnet;

public final class R {
	public static final class anim {
		public static final int slide_down = 0x7f05000a;
		public static final int slide_up = 0x7f05000b;
	}
	public static final class dimen {
		public static final int default_padding_bottom = 0x7f08005e;
	}
	public static final class drawable {
		public static final int bottom_shadow = 0x7f020049;
		public static final int ic_launcher = 0x7f020078;
		public static final int trash = 0x7f020082;
	}
	public static final class id {
		public static final int action_settings = 0x7f0d00bd;
		public static final int shadow = 0x7f0d00b9;
		public static final int xButton = 0x7f0d00ba;
		public static final int xButtonImg = 0x7f0d00bb;
	}
	public static final class layout {
		public static final int x_button_holder = 0x7f040045;
	}
	public static final class menu {
		public static final int paranormal = 0x7f0e0002;
	}
	public static final class string {
		public static final int action_settings = 0x7f060028;
		public static final int app_name = 0x7f06002c;
		public static final int hello_world = 0x7f060044;
	}
	public static final class style {
		public static final int AppTheme = 0x7f090083;
	}
}
