/* AUTO-GENERATED FILE.  DO NOT MODIFY.
*
* This class was automatically generated by the
* aapt tool from the resource data it found.  It
* should not be modified by hand.
*/

package com.nilecon.playmobilesdk;
import com.asiasoft.playparksdk.PPSWebViewActivity;

import android.content.Context;

public final class R {
	
	private static int getResourcesId(String resName, String resType){
	   Context context = PPSWebViewActivity.context;
	   return context.getResources().getIdentifier(resName, resType, context.getPackageName());
	}
	  
   public static final class attr {
   }
   public static final class color {
       public static final int alpha_black=getResourcesId("alpha_black", "color");//40014;
       public static final int aqua=getResourcesId("aqua", "color");//4000c;
       public static final int black=getResourcesId("black", "color");//40013;
       public static final int blue=getResourcesId("blue", "color");//40011;
       public static final int dark_brown=getResourcesId("dark_brown", "color");//40016;
       public static final int dark_gray=getResourcesId("dark_gray", "color");//40007;
       public static final int dark_orange=getResourcesId("dark_orange", "color");//40018;
       public static final int dimmer_black=getResourcesId("dimmer_black", "color");//40015;
       public static final int dimmer_gray=getResourcesId("dimmer_gray", "color");//40008;
       public static final int fuchsia=getResourcesId("fuchsia", "color");//40003;
       public static final int gray=getResourcesId("gray", "color");//40006;
       public static final int green=getResourcesId("green", "color");//4000f;
       public static final int leaf=getResourcesId("leaf", "color");//40010;
       public static final int lime=getResourcesId("lime", "color");//4000d;
       public static final int maroon=getResourcesId("maroon", "color");//4000b;
       public static final int navy=getResourcesId("navy", "color");//40012;
       public static final int olive=getResourcesId("olive", "color");//40009;
       public static final int orange=getResourcesId("orange", "color");//40017;
       public static final int pps_action_bar=getResourcesId("pps_action_bar", "color");//40019;
       public static final int purple=getResourcesId("purple", "color");//4000a;
       public static final int red=getResourcesId("red", "color");//40004;
       public static final int silver=getResourcesId("silver", "color");//40005;
       public static final int teal=getResourcesId("teal", "color");//4000e;
       public static final int transparent=getResourcesId("transparent", "color");//40000;
       public static final int white=getResourcesId("white", "color");//40001;
       public static final int yellow=getResourcesId("yellow", "color");//40002;
   }
   public static final class dimen {
       public static final int pps_action_bar_size=getResourcesId("pps_action_bar_size", "dimen");//50000;
       public static final int pps_action_button_min_width=getResourcesId("pps_action_button_min_width", "dimen");//50001;
       /**  equal pps_action_bar_size of value-large/dimens.xml 
        */
       public static final int pps_action_button_padding_rl=getResourcesId("pps_action_button_padding_rl", "dimen");//50002;
   }
   public static final class drawable {
       public static final int ic_launcher=getResourcesId("ic_launcher", "drawable");//20000;
       public static final int pps_close_button=getResourcesId("pps_close_button", "drawable");//20001;
       public static final int pps_close_button_pressed=getResourcesId("pps_close_button_pressed", "drawable");//20002;
       public static final int pps_close_button_selector=getResourcesId("pps_close_button_selector", "drawable");//20003;
   }
   public static final class id {
       public static final int BindAccount=getResourcesId("BindAccount", "id");//80002;
       public static final int Init=getResourcesId("Init", "id");//80000;
       public static final int Login=getResourcesId("Login", "id");//80001;
       public static final int action_bar_title_text_view=getResourcesId("action_bar_title_text_view", "id");//80004;
       public static final int close_button=getResourcesId("close_button", "id");//80005;
       public static final int container=getResourcesId("container", "id");//80003;
       public static final int web_view=getResourcesId("web_view", "id");//80006;
   }
   public static final class layout {
       public static final int pps_activity_web_view=getResourcesId("pps_activity_web_view", "layout");//30001;
   }
   public static final class string {
       public static final int app_name=getResourcesId("app_name", "string");//60000;
       public static final int pps_action_mode_bind_account=getResourcesId("pps_action_mode_bind_account", "string");//60005;
       public static final int pps_action_mode_login=getResourcesId("pps_action_mode_login", "string");//60003;
       public static final int pps_action_mode_payment=getResourcesId("pps_action_mode_payment", "string");//60007;
       public static final int pps_action_mode_switch_account=getResourcesId("pps_action_mode_switch_account", "string");//60004;
       public static final int pps_action_mode_wallet_payment=getResourcesId("pps_action_mode_wallet_payment", "string");//60006;
       public static final int pps_action_mode_web_top_up=getResourcesId("pps_action_mode_web_top_up", "string");//60008;
       /**  PlayPark SDK 
<string name="app_name">PlayparkSDK</string>
        */
       public static final int pps_content_desc=getResourcesId("getResourcesId", "string");//60001;
       public static final int pps_content_desc_close_button=getResourcesId("pps_content_desc_close_button", "string");//60002;
       public static final int pps_dialog_invalid_action_mode_message=getResourcesId("pps_dialog_invalid_action_mode_message", "string");//60016;
       public static final int pps_dialog_invalid_action_mode_title=getResourcesId("pps_dialog_invalid_action_mode_title", "string");//60015;
       public static final int pps_dialog_invalid_config_message=getResourcesId("pps_dialog_invalid_config_message", "string");//60018;
       public static final int pps_dialog_invalid_config_title=getResourcesId("pps_dialog_invalid_config_title", "string");//60017;
       public static final int pps_dialog_loading_failed_message=getResourcesId("pps_dialog_loading_failed_message", "string");//60014;
       public static final int pps_dialog_loading_failed_title=getResourcesId("pps_dialog_loading_failed_title", "string");//60013;
       public static final int pps_no_internet_connection=getResourcesId("pps_no_internet_connection_message", "string");//6000e;
       public static final int pps_no_internet_connection_message=getResourcesId("pps_no_internet_connection_message", "string");//6000a;
       public static final int pps_no_internet_connection_title=getResourcesId("pps_no_internet_connection_title", "string");//60009;
       public static final int pps_progress_message=getResourcesId("pps_progress_message", "string");//60012;
       public static final int pps_progress_title=getResourcesId("pps_progress_title", "string");//60011;
       public static final int pps_retry_button=getResourcesId("pps_retry_button", "string");//60019;
       public static final int pps_timeout=getResourcesId("pps_timeout", "string");//6000f;
       public static final int pps_uninitialized_sdk_login=getResourcesId("pps_uninitialized_sdk_login", "string");//6000b;
       public static final int pps_uninitialized_sdk_payment=getResourcesId("pps_uninitialized_sdk_payment", "string");//6000d;
       public static final int pps_uninitialized_sdk_wallet_payment=getResourcesId("pps_uninitialized_sdk_wallet_payment", "string");//6000c;
       public static final int pps_user_cancelled=getResourcesId("pps_user_cancelled", "string");//60010;
   }
   public static final class style {
       /** 
           Theme customizations available in newer API levels can go in
           res/values-vXX/styles.xml, while customizations related to
           backward-compatibility can go here.
       

       Base application theme for API 11+. This theme completely replaces
       AppBaseTheme from res/values/styles.xml on API 11+ devices.
   
API 11 theme customizations can go here. 

       Base application theme for API 14+. This theme completely replaces
       AppBaseTheme from BOTH res/values/styles.xml and
       res/values-v11/styles.xml on API 14+ devices.
   
API 14 theme customizations can go here. 
        */
       public static final int AppBaseTheme=getResourcesId("AppBaseTheme", "style");//70000;
       /**  Application theme. 
All customizations that are NOT specific to a particular API-level can go here. 
        */
       public static final int AppTheme=getResourcesId("AppTheme", "style");//70001;
       public static final int FullScreenTheme=getResourcesId("FullScreenTheme", "style");//70002;
       public static final int PPS_ActionBar_TitleText=getResourcesId("PPS_ActionBar_TitleText", "style");//70003;
   }
}
